In [1]:
import numpy as np

For loops vs Numpy
<br>
Let's take a look at how Numpy's built in mathematical functions save us a lot of time by making looping redundant

In [46]:
#core/src/multiarray/ctors.c
%time x = np.arange(100000)
%time y = list(range(100000))


Wall time: 0 ns
Wall time: 2.99 ms


In [47]:
%time np.sum(x)

Wall time: 0 ns


704982704

In [50]:
%%time
mean = np.average(x)

Wall time: 0 ns


In [51]:
%%time 
total = 0
count = 0
for _ in y:
    total += _
    count += _
    
total / count

Wall time: 22.7 ms


1.0

Which one do you think is faster?
<br>
abs(3.14159) or np.abs(3.14159)

In [52]:
%time abs(-3.14159)
%time np.abs(-3.14159)

Wall time: 0 ns
Wall time: 0 ns


3.14159

Now which one of these do you think is faster? <br>
abs([-1, 2, -3, -1, -4] or np.abs([-1, 2, -3, -1, -4])

In [53]:
%time [abs(x) for x in [-1, 2, -3, -1, -4] * 100]
%time np.abs([-1, 2, -3, -1, -4] * 100)

Wall time: 0 ns
Wall time: 0 ns


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Surprised? How about this

In [54]:
array = np.array([-1, 2, -3, -1, -4] * 100)
%time [abs(x) for x in array]
%time np.abs(array)

Wall time: 0 ns
Wall time: 0 ns


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Stride tricks with numpy. <br><br>
Sliding Window

In [55]:
a = np.arange(10)
s = 2
w = 4
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [57]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )[::s]

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

Short aside - <br>
`[::]` was added to Python at the request of the developers of Numerical Python, which uses the third argument extensively.

In [58]:
a = np.arange(20).reshape(5, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [59]:
np.lib.stride_tricks.as_strided(a, shape = (15, 2, 2), strides = (8, 32, 8))[::2]

array([[[         0,          2],
        [         8,         10]],

       [[         4,          6],
        [        12,         14]],

       [[         8,         10],
        [        16,         18]],

       [[        12,         14],
        [1551068448, -557860107]],

       [[        16,         18],
        [-422175632, -422175632]],

       [[1551068448, -557860107],
        [         0,          1]],

       [[-422175632, -422175632],
        [         2,          0]],

       [[         0,          1],
        [-422274112,          9]]])

Instead of striding using [::2], chagne the shape and strides in as_strided to create same effect.

In [60]:
np.lib.stride_tricks.as_strided(a, shape = (8, 2, 2), strides = (16, 32, 8))

array([[[         0,          2],
        [         8,         10]],

       [[         4,          6],
        [        12,         14]],

       [[         8,         10],
        [        16,         18]],

       [[        12,         14],
        [1551068448, -557860107]],

       [[        16,         18],
        [-422175632, -422175632]],

       [[1551068448, -557860107],
        [         0,          1]],

       [[-422175632, -422175632],
        [         2,          0]],

       [[         0,          1],
        [-422274112,          9]]])

In [61]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

How do these arrays look in memory?

![alt text](NDArray_structure.png "NDArray Structure")

In [62]:
x.__array_interface__

{'data': (2043984201120, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (10,),
 'version': 3}

In [63]:
y = np.lib.stride_tricks.as_strided(x, shape = (9, 2), strides = x.strides * 2)

In [64]:
y

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6],
       [6, 7],
       [7, 8],
       [8, 9]])

In [65]:
y.__array_interface__

{'data': (2043984201120, False),
 'strides': (4, 4),
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (9, 2),
 'version': 3}

Einsum <br>
dot, diagonal, trace, sum, matrix multiplication

In [66]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

Return a view of the matrix

In [67]:
np.einsum('ij -> i', A) 

array([ 3,  6, 15])

In [68]:
A.view()

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

Matrix Transpose (doesn't work if you want to switch around axes in 3D etc.)

In [69]:
np.einsum('ij -> ji', A)

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

In [70]:
A.T

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

Matrix Diagonal

In [71]:
%time np.einsum('ii->i', A)

Wall time: 0 ns


array([1, 2, 5])

In [72]:
%time np.diag(A)

Wall time: 0 ns


array([1, 2, 5])

Matrix Trace

In [73]:
%time np.einsum('ii -> ', A)

Wall time: 0 ns


8

Sum along an axis <br> You try!

In [74]:
%time np.einsum('ij->i', A)
%time np.sum(A, axis=1)

Wall time: 0 ns
Wall time: 0 ns


array([ 3,  6, 15])

Matrix and element-wise multiplication.

In [75]:
A * B

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [76]:
np.einsum('ij, ij -> ij', A, B)

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [77]:
A @ B

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [78]:
%time np.einsum('ij, jk-> ik', A, B)

Wall time: 0 ns


array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [79]:
%time np.dot(A, B)

Wall time: 0 ns


array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

Using Einsum and stride tricks to do a convultion operation!

In [80]:
matrix = np.arange(25).reshape((5, 5))
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [81]:
conv_filter = np.array([[1, 1, 0], [1, 2, 3], [0, 1, 1]])
print(conv_filter)

[[1 1 0]
 [1 2 3]
 [0 1 1]]


In [82]:
filter_shape = conv_filter.shape
conv_shape   = tuple(np.subtract(matrix.shape, filter_shape) + 1) + filter_shape
conv_strides = matrix.strides * 2
print(conv_shape)
print(conv_strides)

(3, 3, 3, 3)
(20, 4, 20, 4)


In [83]:
sub_matrices = np.lib.stride_tricks.as_strided(matrix, conv_shape, conv_strides)

In [84]:
print(sub_matrices)

[[[[ 0  1  2]
   [ 5  6  7]
   [10 11 12]]

  [[ 1  2  3]
   [ 6  7  8]
   [11 12 13]]

  [[ 2  3  4]
   [ 7  8  9]
   [12 13 14]]]


 [[[ 5  6  7]
   [10 11 12]
   [15 16 17]]

  [[ 6  7  8]
   [11 12 13]
   [16 17 18]]

  [[ 7  8  9]
   [12 13 14]
   [17 18 19]]]


 [[[10 11 12]
   [15 16 17]
   [20 21 22]]

  [[11 12 13]
   [16 17 18]
   [21 22 23]]

  [[12 13 14]
   [17 18 19]
   [22 23 24]]]]


In [85]:
convolved = np.einsum('ij, ijkl->kl', conv_filter, sub_matrices)

In [86]:
print(convolved)

[[ 62  72  82]
 [112 122 132]
 [162 172 182]]
